-- ===============================================================
-- Make WELLNESS fully English: exercise names + muscle groups (catalog &
-- history), day names (Día N -> Day N), workout titles, and plan objective.
-- Plan days link exercises by id, so they pick up the new names automatically.
-- Run once; safe to re-run.
-- ===============================================================
do $$
declare uid uuid; pid uuid;
begin
  select id into uid from users where lower(email) = lower('yaczoe@gmail.com');
  if uid is null then raise exception 'Registra yaczoe@gmail.com primero.'; end if;
  select id into pid from plans where user_id = uid and name = 'WELLNESS' limit 1;
  update exercises set name = 'V-Ups' where (owner_id is null or owner_id = uid) and name = 'Abdominales en V';
  update workout_sets ws set exercise_name = 'V-Ups' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Abdominales en V';
  update exercises set name = 'Cable Hip Abduction (Mid-Pulley)' where (owner_id is null or owner_id = uid) and name = 'Abducción de cadera en polea a media altura';
  update workout_sets ws set exercise_name = 'Cable Hip Abduction (Mid-Pulley)' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Abducción de cadera en polea a media altura';
  update exercises set name = 'Seated Hip Abduction Machine' where (owner_id is null or owner_id = uid) and name = 'Abducción de cadera sentado en máquina';
  update workout_sets ws set exercise_name = 'Seated Hip Abduction Machine' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Abducción de cadera sentado en máquina';
  update exercises set name = 'Single-Arm Lateral Raise (Long Partials)' where (owner_id is null or owner_id = uid) and name = 'Abducción unilateral de hombro - parciales largas';
  update workout_sets ws set exercise_name = 'Single-Arm Lateral Raise (Long Partials)' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Abducción unilateral de hombro - parciales largas';
  update exercises set name = 'Seated Hip Adduction Machine' where (owner_id is null or owner_id = uid) and name = 'Aducción de cadera sentado en máquina';
  update workout_sets ws set exercise_name = 'Seated Hip Adduction Machine' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Aducción de cadera sentado en máquina';
  update exercises set name = 'Cable Pullover' where (owner_id is null or owner_id = uid) and name = 'Cable Pull Over';
  update workout_sets ws set exercise_name = 'Cable Pullover' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Cable Pull Over';
  update exercises set name = 'Standing EZ-Bar Biceps Curl' where (owner_id is null or owner_id = uid) and name = 'Curl para bíceps de pie con barra Z';
  update workout_sets ws set exercise_name = 'Standing EZ-Bar Biceps Curl' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Curl para bíceps de pie con barra Z';
  update exercises set name = 'Standing EZ-Bar Biceps Curl' where (owner_id is null or owner_id = uid) and name = 'Curl para bíceps de pie con barra Z1';
  update workout_sets ws set exercise_name = 'Standing EZ-Bar Biceps Curl' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Curl para bíceps de pie con barra Z1';
  update exercises set name = 'Lying Leg Curl Machine' where (owner_id is null or owner_id = uid) and name = 'Curl para isquiosurales acostado en máquina';
  update workout_sets ws set exercise_name = 'Lying Leg Curl Machine' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Curl para isquiosurales acostado en máquina';
  update exercises set name = 'Seated Leg Curl Machine' where (owner_id is null or owner_id = uid) and name = 'Curl para isquiosurales sentado en máquina';
  update workout_sets ws set exercise_name = 'Seated Leg Curl Machine' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Curl para isquiosurales sentado en máquina';
  update exercises set name = 'Barbell Lunges (Quad-Focus)' where (owner_id is null or owner_id = uid) and name = 'Desplantes con barra (cuádriceps)';
  update workout_sets ws set exercise_name = 'Barbell Lunges (Quad-Focus)' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Desplantes con barra (cuádriceps)';
  update exercises set name = 'Eccentric Dragon Flag' where (owner_id is null or owner_id = uid) and name = 'Dragon flag excéntrica';
  update workout_sets ws set exercise_name = 'Eccentric Dragon Flag' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Dragon flag excéntrica';
  update exercises set name = 'Standing Alternating Dumbbell Front Raises' where (owner_id is null or owner_id = uid) and name = 'Elevaciones frontales de pie alternado con mancuernas';
  update workout_sets ws set exercise_name = 'Standing Alternating Dumbbell Front Raises' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Elevaciones frontales de pie alternado con mancuernas';
  update exercises set name = 'Single-Arm Incline Dumbbell Lateral Raise' where (owner_id is null or owner_id = uid) and name = 'Elevaciones laterales de lado a una mano con mancuerna en banco inclinado';
  update workout_sets ws set exercise_name = 'Single-Arm Incline Dumbbell Lateral Raise' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Elevaciones laterales de lado a una mano con mancuerna en banco inclinado';
  update exercises set name = 'Standing Dumbbell Lateral Raises' where (owner_id is null or owner_id = uid) and name = 'Elevaciones laterales de pie con mancuernas';
  update workout_sets ws set exercise_name = 'Standing Dumbbell Lateral Raises' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Elevaciones laterales de pie con mancuernas';
  update exercises set name = 'Hanging Knee Raises' where (owner_id is null or owner_id = uid) and name = 'Elevación de rodillas colgando';
  update workout_sets ws set exercise_name = 'Hanging Knee Raises' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Elevación de rodillas colgando';
  update exercises set name = 'Seated Calf Raise' where (owner_id is null or owner_id = uid) and name = 'Elevación de talones en costurera';
  update workout_sets ws set exercise_name = 'Seated Calf Raise' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Elevación de talones en costurera';
  update exercises set name = 'Calf Raise on 45° Leg Press (Lengthened Partials)' where (owner_id is null or owner_id = uid) and name = 'Elevación de talón en prensa a 45° parciales en elongación';
  update workout_sets ws set exercise_name = 'Calf Raise on 45° Leg Press (Lengthened Partials)' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Elevación de talón en prensa a 45° parciales en elongación';
  update exercises set name = 'Behind-the-Back Cable Lateral Raise (Mid-Height)' where (owner_id is null or owner_id = uid) and name = 'Elevación lateral con polea detrás del cuerpo (media altura)';
  update workout_sets ws set exercise_name = 'Behind-the-Back Cable Lateral Raise (Mid-Height)' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Elevación lateral con polea detrás del cuerpo (media altura)';
  update exercises set name = 'Single-Leg Leg Extension Machine' where (owner_id is null or owner_id = uid) and name = 'Extensión de rodilla unilateral en máquina';
  update workout_sets ws set exercise_name = 'Single-Leg Leg Extension Machine' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Extensión de rodilla unilateral en máquina';
  update exercises set name = '45° Back Extension' where (owner_id is null or owner_id = uid) and name = 'Extensión de tronco en banco romano a 45°';
  update workout_sets ws set exercise_name = '45° Back Extension' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Extensión de tronco en banco romano a 45°';
  update exercises set name = 'Seated Leg Extension Machine' where (owner_id is null or owner_id = uid) and name = 'Extensión para cuádriceps sentado en máquina';
  update workout_sets ws set exercise_name = 'Seated Leg Extension Machine' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Extensión para cuádriceps sentado en máquina';
  update exercises set name = 'Incline Hammer Curl' where (owner_id is null or owner_id = uid) and name = 'Hammer curl inclinado';
  update workout_sets ws set exercise_name = 'Incline Hammer Curl' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Hammer curl inclinado';
  update exercises set name = 'Single-Leg Dumbbell Hip Thrust' where (owner_id is null or owner_id = uid) and name = 'Hip Thrust a Una Pierna con Mancuerna';
  update workout_sets ws set exercise_name = 'Single-Leg Dumbbell Hip Thrust' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Hip Thrust a Una Pierna con Mancuerna';
  update exercises set name = 'Machine Hip Thrust' where (owner_id is null or owner_id = uid) and name = 'Hip thrust tradicional en máquina';
  update workout_sets ws set exercise_name = 'Machine Hip Thrust' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Hip thrust tradicional en máquina';
  update exercises set name = 'Cable JM Press' where (owner_id is null or owner_id = uid) and name = 'JM Press con cable';
  update workout_sets ws set exercise_name = 'Cable JM Press' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'JM Press con cable';
  update exercises set name = 'Neutral-Grip Lat Pulldown' where (owner_id is null or owner_id = uid) and name = 'Jalón al pecho con agarre neutro';
  update workout_sets ws set exercise_name = 'Neutral-Grip Lat Pulldown' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Jalón al pecho con agarre neutro';
  update exercises set name = 'Runner Glute Kickback' where (owner_id is null or owner_id = uid) and name = 'Patada de corredora';
  update workout_sets ws set exercise_name = 'Runner Glute Kickback' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Patada de corredora';
  update exercises set name = 'Low-Pulley Cable Glute Kickback' where (owner_id is null or owner_id = uid) and name = 'Patada para glúteo con grillete en polea baja';
  update workout_sets ws set exercise_name = 'Low-Pulley Cable Glute Kickback' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Patada para glúteo con grillete en polea baja';
  update exercises set name = 'Stiff-Leg Barbell Romanian Deadlift' where (owner_id is null or owner_id = uid) and name = 'Peso muerto rumano con barra, piernas rígidas.';
  update workout_sets ws set exercise_name = 'Stiff-Leg Barbell Romanian Deadlift' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Peso muerto rumano con barra, piernas rígidas.';
  update exercises set name = 'Stiff-Leg Dumbbell Romanian Deadlift' where (owner_id is null or owner_id = uid) and name = 'Peso muerto rumano con mancuernas - piernas rígidas';
  update workout_sets ws set exercise_name = 'Stiff-Leg Dumbbell Romanian Deadlift' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Peso muerto rumano con mancuernas - piernas rígidas';
  update exercises set name = 'Seated Dumbbell Shoulder Press' where (owner_id is null or owner_id = uid) and name = 'Prensa militar sentado con mancuernas';
  update workout_sets ws set exercise_name = 'Seated Dumbbell Shoulder Press' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Prensa militar sentado con mancuernas';
  update exercises set name = '45° Incline Leg Press' where (owner_id is null or owner_id = uid) and name = 'Prensa para pierna inclinada a 45°';
  update workout_sets ws set exercise_name = '45° Incline Leg Press' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Prensa para pierna inclinada a 45°';
  update exercises set name = 'Single-Arm Seated Machine Row' where (owner_id is null or owner_id = uid) and name = 'Remo a una mano sentado en máquina';
  update workout_sets ws set exercise_name = 'Single-Arm Seated Machine Row' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Remo a una mano sentado en máquina';
  update exercises set name = 'Standing Barbell Row' where (owner_id is null or owner_id = uid) and name = 'Remo horizontal de pie con barra';
  update workout_sets ws set exercise_name = 'Standing Barbell Row' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Remo horizontal de pie con barra';
  update exercises set name = 'Dumbbell Bulgarian Split Squat' where (owner_id is null or owner_id = uid) and name = 'Sentadilla búlgara con mancuerna';
  update workout_sets ws set exercise_name = 'Dumbbell Bulgarian Split Squat' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Sentadilla búlgara con mancuerna';
  update exercises set name = 'Dumbbell Bulgarian Split Squat (Glute)' where (owner_id is null or owner_id = uid) and name = 'Sentadilla búlgara con mancuerna (glúteo)';
  update workout_sets ws set exercise_name = 'Dumbbell Bulgarian Split Squat (Glute)' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Sentadilla búlgara con mancuerna (glúteo)';
  update exercises set name = 'Hack Squat' where (owner_id is null or owner_id = uid) and name = 'Sentadilla hack';
  update workout_sets ws set exercise_name = 'Hack Squat' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'Sentadilla hack';
  update exercises set name = 'Bird Dog' where (owner_id is null or owner_id = uid) and name = 'bird dog';
  update workout_sets ws set exercise_name = 'Bird Dog' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'bird dog';
  update exercises set name = 'Pendulum Squat' where (owner_id is null or owner_id = uid) and name = 'sentadilla pendular';
  update workout_sets ws set exercise_name = 'Pendulum Squat' from workouts w where ws.workout_id = w.id and w.user_id = uid and ws.exercise_name = 'sentadilla pendular';
  update exercises set muscle_group = 'Abs' where (owner_id is null or owner_id = uid) and muscle_group = 'Abdomen';
  update exercises set muscle_group = 'Adductors' where (owner_id is null or owner_id = uid) and muscle_group = 'Aductores de cadera';
  update exercises set muscle_group = 'Biceps' where (owner_id is null or owner_id = uid) and muscle_group = 'Biceps';
  update exercises set muscle_group = 'Core' where (owner_id is null or owner_id = uid) and muscle_group = 'Core';
  update exercises set muscle_group = 'Quads' where (owner_id is null or owner_id = uid) and muscle_group = 'Cuadriceps';
  update exercises set muscle_group = 'Quads' where (owner_id is null or owner_id = uid) and muscle_group = 'Cuádriceps';
  update exercises set muscle_group = 'Lats' where (owner_id is null or owner_id = uid) and muscle_group = 'Dorsales';
  update exercises set muscle_group = 'Back' where (owner_id is null or owner_id = uid) and muscle_group = 'Espalda';
  update exercises set muscle_group = 'Upper Back' where (owner_id is null or owner_id = uid) and muscle_group = 'Espalda Alta';
  update exercises set muscle_group = 'Upper Back' where (owner_id is null or owner_id = uid) and muscle_group = 'Espalda alta';
  update exercises set muscle_group = 'Glutes' where (owner_id is null or owner_id = uid) and muscle_group = 'Gluteos';
  update exercises set muscle_group = 'Glutes' where (owner_id is null or owner_id = uid) and muscle_group = 'Glúteos';
  update exercises set muscle_group = 'Front Delts' where (owner_id is null or owner_id = uid) and muscle_group = 'Hombro anterior';
  update exercises set muscle_group = 'Side Delts' where (owner_id is null or owner_id = uid) and muscle_group = 'Hombro lateral';
  update exercises set muscle_group = 'Side Delts' where (owner_id is null or owner_id = uid) and muscle_group = 'Hombro medio';
  update exercises set muscle_group = 'Rear Delts' where (owner_id is null or owner_id = uid) and muscle_group = 'Hombro posterior';
  update exercises set muscle_group = 'Hamstrings' where (owner_id is null or owner_id = uid) and muscle_group = 'Isquios';
  update exercises set muscle_group = 'Hamstrings' where (owner_id is null or owner_id = uid) and muscle_group = 'Isquiosurales';
  update exercises set muscle_group = 'Calves' where (owner_id is null or owner_id = uid) and muscle_group = 'Pantorrilla';
  update exercises set muscle_group = 'Triceps' where (owner_id is null or owner_id = uid) and muscle_group = 'Triceps';
  update exercises set muscle_group = 'Triceps' where (owner_id is null or owner_id = uid) and muscle_group = 'Tríceps';
  if pid is not null then
    update plan_days d set name = replace(d.name, 'Día ', 'Day ')
      from plan_weeks w where d.week_id = w.id and w.plan_id = pid and d.name like 'Día %';
    update plans set objective = 'Wellness accumulation & deload' where id = pid;
  end if;
  update workouts set title = replace(title, 'Día ', 'Day ') where user_id = uid and title like '%Día %';
  raise notice 'WELLNESS traducido a inglés (ejercicios, grupos, días, títulos).';
end $$;
