-- ─────────────────────────────────────────────────────────────
-- Build the WELLNESS plan structure: 8 weeks -> days (Día N) -> exercises
-- with targets (sets / reps range / RIR), derived from Claudia's log.
-- Run AFTER the schema files; safe to re-run (rebuilds the structure only,
-- never touches logged workouts). Creates the account-linked WELLNESS plan.
-- ─────────────────────────────────────────────────────────────
do $$
declare uid uuid; pid uuid;
begin
  select id into uid from users where lower(email) = lower('yaczoe@gmail.com');
  if uid is null then raise exception 'Registra yaczoe@gmail.com primero.'; end if;

  select id into pid from plans where user_id = uid and name = 'WELLNESS' limit 1;
  if pid is null then
    insert into plans (user_id, name, objective, weeks, end_date, is_active, current_week, next_index)
    values (uid, 'WELLNESS', 'Wellness accumulation & deload', 8, '2026-06-30', true, 0, 0)
    returning id into pid;
    update plans set is_active = (id = pid) where user_id = uid;
  end if;

  create temp table pstruct(wpos int, wname text, dpos int, dname text, epos int, ename text, egrp text, sets int, reps text, rir text) on commit drop;
  insert into pstruct values
(0, 'Come back', 0, 'Day 1', 0, 'Single-Leg Dumbbell Hip Thrust', 'Glutes', 2, '12', '1'),
(0, 'Come back', 0, 'Day 1', 1, 'Barbell Lunges (Quad-Focus)', 'Quads', 3, '8', '0-1'),
(0, 'Come back', 0, 'Day 1', 2, 'Single-Leg Leg Extension Machine', 'Quads', 4, '12-15', 'fallo'),
(0, 'Come back', 0, 'Day 1', 3, 'Stiff-Leg Barbell Romanian Deadlift', 'Glutes', 2, '8', '2'),
(0, 'Come back', 0, 'Day 1', 4, 'Lying Leg Curl Machine', 'Hamstrings', 2, '8-9', '0-1'),
(0, 'Come back', 0, 'Day 1', 5, 'Cable Hip Abduction (Mid-Pulley)', 'Glutes', 2, '10', '0-1'),
(0, 'Come back', 0, 'Day 1', 6, 'Calf Raise on 45° Leg Press (Lengthened Partials)', 'Calves', 2, '14', '0-1'),
(0, 'Come back', 1, 'Day 2', 0, 'Neutral-Grip Lat Pulldown', 'Back', 2, '7-8', '0'),
(0, 'Come back', 1, 'Day 2', 1, 'Single-Arm Seated Machine Row', 'Back', 2, '8-9', '0-1'),
(0, 'Come back', 1, 'Day 2', 2, 'Incline Hammer Curl', 'Biceps', 2, '10-11', '0-1'),
(0, 'Come back', 1, 'Day 2', 3, 'Standing EZ-Bar Biceps Curl', 'Biceps', 2, '10-11', '0'),
(0, 'Come back', 1, 'Day 2', 4, 'V-Ups', 'Core', 2, '15', '0-1'),
(0, 'Come back', 1, 'Day 2', 5, 'Hanging Knee Raises', 'Core', 2, '6', '0-1'),
(0, 'Come back', 2, 'Day 3', 0, 'Hack Squat', 'Quads', 2, '7-8', '1-2'),
(0, 'Come back', 2, 'Day 3', 1, 'Dumbbell Bulgarian Split Squat', 'Glutes', 2, '8-9', '0-1'),
(0, 'Come back', 2, 'Day 3', 2, 'Seated Leg Extension Machine', 'Quads', 3, '10-11', '0'),
(0, 'Come back', 2, 'Day 3', 3, '45° Back Extension', 'Glutes', 3, '12-13', '0'),
(0, 'Come back', 2, 'Day 3', 4, 'Seated Hip Abduction Machine', 'Glutes', 2, '2-12', '0-1'),
(0, 'Come back', 2, 'Day 3', 5, 'Lying Leg Curl Machine', 'Hamstrings', 3, '6-7', '0'),
(0, 'Come back', 3, 'Day 4', 0, 'Seated Dumbbell Shoulder Press', 'Front Delts', 2, '6-7', '0-1'),
(0, 'Come back', 3, 'Day 4', 1, 'Standing Dumbbell Lateral Raises', 'Side Delts', 2, '15', '0'),
(0, 'Come back', 3, 'Day 4', 2, 'Cable JM Press', 'Triceps', 2, '7-9', '0'),
(0, 'Come back', 3, 'Day 4', 3, 'Eccentric Dragon Flag', 'Core', 2, '10-12', '0-1'),
(0, 'Come back', 3, 'Day 4', 4, 'Bird Dog', 'Core', 2, '10', '0-1'),
(0, 'Come back', 4, 'Day 5', 0, 'Pendulum Squat', 'Quads', 3, '9-10', '0-1'),
(0, 'Come back', 4, 'Day 5', 1, 'Seated Leg Extension Machine', 'Quads', 3, '8-11', '0-1'),
(0, 'Come back', 4, 'Day 5', 2, 'Machine Hip Thrust', 'Glutes', 2, '9-10', '0-1'),
(0, 'Come back', 4, 'Day 5', 3, 'Low-Pulley Cable Glute Kickback', 'Glutes', 2, '12', '0'),
(0, 'Come back', 4, 'Day 5', 4, 'Seated Leg Curl Machine', 'Hamstrings', 2, '8', '0-1'),
(0, 'Come back', 4, 'Day 5', 5, 'Cable Pullover', 'Lats', 2, '8-10', '0-1'),
(1, 'Yellow Ledbetter', 0, 'Day 1', 0, 'Single-Leg Dumbbell Hip Thrust', 'Glutes', 2, '14', '0-1'),
(1, 'Yellow Ledbetter', 0, 'Day 1', 1, 'Barbell Lunges (Quad-Focus)', 'Quads', 3, '8-9', '0'),
(1, 'Yellow Ledbetter', 0, 'Day 1', 2, 'Single-Leg Leg Extension Machine', 'Quads', 4, '11-14', 'fallo'),
(1, 'Yellow Ledbetter', 0, 'Day 1', 3, 'Stiff-Leg Barbell Romanian Deadlift', 'Glutes', 2, '7-8', '0'),
(1, 'Yellow Ledbetter', 0, 'Day 1', 4, 'Lying Leg Curl Machine', 'Hamstrings', 2, '10-12', '0'),
(1, 'Yellow Ledbetter', 0, 'Day 1', 5, 'Cable Hip Abduction (Mid-Pulley)', 'Glutes', 2, '12', '0'),
(1, 'Yellow Ledbetter', 0, 'Day 1', 6, 'Calf Raise on 45° Leg Press (Lengthened Partials)', 'Calves', 2, '12-14', '0'),
(1, 'Yellow Ledbetter', 1, 'Day 2', 0, 'Neutral-Grip Lat Pulldown', 'Upper Back', 3, '8', '0-1'),
(1, 'Yellow Ledbetter', 1, 'Day 2', 1, 'Behind-the-Back Cable Lateral Raise (Mid-Height)', 'Side Delts', 3, '6-8', '0-1'),
(1, 'Yellow Ledbetter', 1, 'Day 2', 2, 'Standing Alternating Dumbbell Front Raises', 'Front Delts', 3, '14-15', '0-1'),
(1, 'Yellow Ledbetter', 1, 'Day 2', 3, 'Single-Arm Seated Machine Row', 'Lats', 3, '7-8', '0'),
(1, 'Yellow Ledbetter', 1, 'Day 2', 4, 'Standing EZ-Bar Biceps Curl', 'Biceps', 2, '8-10', '0'),
(1, 'Yellow Ledbetter', 1, 'Day 2', 5, 'V-Ups', 'Core', 3, '12', '0-1'),
(1, 'Yellow Ledbetter', 1, 'Day 2', 6, 'Hanging Knee Raises', 'Core', 3, '8', '0-1'),
(1, 'Yellow Ledbetter', 2, 'Day 3', 0, 'Hack Squat', 'Quads', 2, '11-12', '0-1'),
(1, 'Yellow Ledbetter', 2, 'Day 3', 1, 'Dumbbell Bulgarian Split Squat', 'Glutes', 2, '8-9', '0'),
(1, 'Yellow Ledbetter', 2, 'Day 3', 2, 'Seated Leg Extension Machine', 'Quads', 3, '10-11', '0'),
(1, 'Yellow Ledbetter', 2, 'Day 3', 3, '45° Back Extension', 'Glutes', 3, '7-8', '0'),
(1, 'Yellow Ledbetter', 2, 'Day 3', 4, 'Seated Hip Abduction Machine', 'Glutes', 2, '13-14', '0-1'),
(1, 'Yellow Ledbetter', 2, 'Day 3', 5, 'Lying Leg Curl Machine', 'Hamstrings', 3, '5-8', '0-1'),
(1, 'Yellow Ledbetter', 3, 'Day 4', 0, 'Seated Dumbbell Shoulder Press', 'Front Delts', 4, '6', '0'),
(1, 'Yellow Ledbetter', 3, 'Day 4', 1, 'Single-Arm Incline Dumbbell Lateral Raise', 'Side Delts', 3, '10-12', '0'),
(1, 'Yellow Ledbetter', 3, 'Day 4', 2, 'Single-Arm Lateral Raise (Long Partials)', 'Rear Delts', 3, '7-9', '0'),
(1, 'Yellow Ledbetter', 3, 'Day 4', 3, 'Cable JM Press', 'Triceps', 3, '7-8', '0'),
(1, 'Yellow Ledbetter', 3, 'Day 4', 4, 'Eccentric Dragon Flag', 'Core', 4, '6-8', '0-1'),
(1, 'Yellow Ledbetter', 3, 'Day 4', 5, 'Bird Dog', 'Core', 4, '10-12', '0-1'),
(1, 'Yellow Ledbetter', 4, 'Day 5', 0, 'Pendulum Squat', 'Quads', 3, '10-11', '0'),
(1, 'Yellow Ledbetter', 4, 'Day 5', 1, 'Seated Leg Extension Machine', 'Quads', 3, '10-11', '0'),
(1, 'Yellow Ledbetter', 4, 'Day 5', 2, 'Machine Hip Thrust', 'Glutes', 2, '10', '0'),
(1, 'Yellow Ledbetter', 4, 'Day 5', 3, 'Low-Pulley Cable Glute Kickback', 'Glutes', 2, '12-13', '0'),
(1, 'Yellow Ledbetter', 4, 'Day 5', 4, 'Seated Leg Curl Machine', 'Hamstrings', 2, '10-12', '0-1'),
(1, 'Yellow Ledbetter', 4, 'Day 5', 5, 'Cable Pullover', 'Lats', 2, '13-14', '0'),
(2, 'Dont Cry', 0, 'Day 1', 0, 'Single-Leg Dumbbell Hip Thrust', 'Glutes', 2, '12', '0-1'),
(2, 'Dont Cry', 0, 'Day 1', 1, 'Barbell Lunges (Quad-Focus)', 'Quads', 4, '6-8', '0-1'),
(2, 'Dont Cry', 0, 'Day 1', 2, 'Single-Leg Leg Extension Machine', 'Quads', 5, '12-14', '0'),
(2, 'Dont Cry', 0, 'Day 1', 3, 'Lying Leg Curl Machine', 'Hamstrings', 4, '13-16', '0'),
(2, 'Dont Cry', 0, 'Day 1', 4, 'Cable Hip Abduction (Mid-Pulley)', 'Glutes', 3, '12-15', 'fallo'),
(2, 'Dont Cry', 0, 'Day 1', 5, 'Calf Raise on 45° Leg Press (Lengthened Partials)', 'Calves', 4, '14-16', '0'),
(2, 'Dont Cry', 1, 'Day 2', 0, 'Neutral-Grip Lat Pulldown', 'Upper Back', 2, '9', '0-1'),
(2, 'Dont Cry', 1, 'Day 2', 1, 'Behind-the-Back Cable Lateral Raise (Mid-Height)', 'Side Delts', 4, '8-10', '0'),
(2, 'Dont Cry', 1, 'Day 2', 2, 'Standing Alternating Dumbbell Front Raises', 'Front Delts', 3, '16-17', '0'),
(2, 'Dont Cry', 1, 'Day 2', 3, 'Single-Arm Seated Machine Row', 'Lats', 3, '7-8', '0'),
(2, 'Dont Cry', 1, 'Day 2', 4, 'Standing EZ-Bar Biceps Curl', 'Biceps', 2, '11', '0'),
(2, 'Dont Cry', 1, 'Day 2', 5, 'V-Ups', 'Core', 3, '13-14', '0'),
(2, 'Dont Cry', 1, 'Day 2', 6, 'Hanging Knee Raises', 'Core', 3, '10', '0-1'),
(2, 'Dont Cry', 2, 'Day 3', 0, 'Hack Squat', 'Quads', 3, '10-12', '0'),
(2, 'Dont Cry', 2, 'Day 3', 1, 'Dumbbell Bulgarian Split Squat', 'Glutes', 2, '6', '0'),
(2, 'Dont Cry', 2, 'Day 3', 2, 'Seated Leg Extension Machine', 'Quads', 6, '12-13', '0'),
(2, 'Dont Cry', 2, 'Day 3', 3, '45° Back Extension', 'Glutes', 2, '9-10', 'fallo'),
(2, 'Dont Cry', 2, 'Day 3', 4, 'Seated Hip Abduction Machine', 'Glutes', 2, '13', '0-1'),
(2, 'Dont Cry', 2, 'Day 3', 5, 'Lying Leg Curl Machine', 'Hamstrings', 4, '10-13', '0'),
(2, 'Dont Cry', 3, 'Day 4', 0, 'Seated Dumbbell Shoulder Press', 'Front Delts', 4, '5-7', '0'),
(2, 'Dont Cry', 3, 'Day 4', 1, 'Single-Arm Incline Dumbbell Lateral Raise', 'Side Delts', 3, '13-16', '0'),
(2, 'Dont Cry', 3, 'Day 4', 2, 'Single-Arm Lateral Raise (Long Partials)', 'Rear Delts', 3, '10-12', '0'),
(2, 'Dont Cry', 3, 'Day 4', 3, 'Cable JM Press', 'Triceps', 3, '8-9', 'fallo'),
(2, 'Dont Cry', 3, 'Day 4', 4, 'Eccentric Dragon Flag', 'Core', 4, '7-9', '0'),
(2, 'Dont Cry', 3, 'Day 4', 5, 'Bird Dog', 'Core', 4, '12-15', '0-1'),
(2, 'Dont Cry', 4, 'Day 5', 0, 'Pendulum Squat', 'Quads', 3, '5-6', '0'),
(2, 'Dont Cry', 4, 'Day 5', 1, 'Seated Leg Extension Machine', 'Quads', 4, '9-12', 'fallo'),
(2, 'Dont Cry', 4, 'Day 5', 2, 'Machine Hip Thrust', 'Glutes', 2, '9', '0'),
(2, 'Dont Cry', 4, 'Day 5', 3, 'Low-Pulley Cable Glute Kickback', 'Glutes', 2, '8-13', '0'),
(2, 'Dont Cry', 4, 'Day 5', 4, 'Seated Leg Curl Machine', 'Hamstrings', 4, '9-12', '0'),
(2, 'Dont Cry', 4, 'Day 5', 5, 'Cable Pullover', 'Lats', 2, '8-15', '0-1'),
(3, 'November rain', 0, 'Day 1', 0, 'Single-Leg Dumbbell Hip Thrust', 'Glutes', 2, '9-10', '0-1'),
(3, 'November rain', 0, 'Day 1', 1, 'Barbell Lunges (Quad-Focus)', 'Quads', 4, '9-10', '0'),
(3, 'November rain', 0, 'Day 1', 2, 'Single-Leg Leg Extension Machine', 'Quads', 5, '11-14', '0'),
(3, 'November rain', 0, 'Day 1', 3, 'Lying Leg Curl Machine', 'Hamstrings', 4, '8-10', '0-1'),
(3, 'November rain', 0, 'Day 1', 4, 'Cable Hip Abduction (Mid-Pulley)', 'Glutes', 3, '10', '0-1'),
(3, 'November rain', 0, 'Day 1', 5, 'Calf Raise on 45° Leg Press (Lengthened Partials)', 'Calves', 4, '12', '0-1'),
(3, 'November rain', 1, 'Day 2', 0, 'Neutral-Grip Lat Pulldown', 'Upper Back', 2, '9-10', '0-1'),
(3, 'November rain', 1, 'Day 2', 1, 'Behind-the-Back Cable Lateral Raise (Mid-Height)', 'Side Delts', 4, '10-11', '0'),
(3, 'November rain', 1, 'Day 2', 2, 'Standing Alternating Dumbbell Front Raises', 'Front Delts', 3, '20', '0-1'),
(3, 'November rain', 1, 'Day 2', 3, 'Standing EZ-Bar Biceps Curl', 'Biceps', 2, '12', '0'),
(3, 'November rain', 1, 'Day 2', 4, 'V-Ups', 'Core', 3, '15', '0-1'),
(3, 'November rain', 1, 'Day 2', 5, 'Hanging Knee Raises', 'Core', 3, '12-13', '0'),
(3, 'November rain', 2, 'Day 3', 0, 'Hack Squat', 'Quads', 3, '9-10', '0'),
(3, 'November rain', 2, 'Day 3', 1, 'Dumbbell Bulgarian Split Squat', 'Glutes', 2, '7-9', '0'),
(3, 'November rain', 2, 'Day 3', 2, 'Seated Leg Extension Machine', 'Quads', 6, '11-13', 'fallo'),
(3, 'November rain', 2, 'Day 3', 3, '45° Back Extension', 'Glutes', 2, '6', 'fallo'),
(3, 'November rain', 2, 'Day 3', 4, 'Seated Hip Abduction Machine', 'Glutes', 2, '11', '0-1'),
(3, 'November rain', 2, 'Day 3', 5, 'Lying Leg Curl Machine', 'Hamstrings', 4, '10-12', '0'),
(3, 'November rain', 3, 'Day 4', 0, 'Seated Dumbbell Shoulder Press', 'Front Delts', 4, '5-8', '0'),
(3, 'November rain', 3, 'Day 4', 1, 'Single-Arm Incline Dumbbell Lateral Raise', 'Side Delts', 3, '14-15', '0'),
(3, 'November rain', 3, 'Day 4', 2, 'Single-Arm Lateral Raise (Long Partials)', 'Rear Delts', 3, '12-14', '0'),
(3, 'November rain', 3, 'Day 4', 3, 'Cable JM Press', 'Triceps', 3, '9', '0'),
(3, 'November rain', 3, 'Day 4', 4, 'Eccentric Dragon Flag', 'Core', 4, '10-11', '0'),
(3, 'November rain', 3, 'Day 4', 5, 'Bird Dog', 'Core', 4, '12', '0-1'),
(3, 'November rain', 4, 'Day 5', 0, 'Pendulum Squat', 'Quads', 3, '6', '0'),
(3, 'November rain', 4, 'Day 5', 1, 'Seated Leg Extension Machine', 'Quads', 4, '9-12', 'fallo'),
(3, 'November rain', 4, 'Day 5', 2, 'Machine Hip Thrust', 'Glutes', 2, '9', '0'),
(3, 'November rain', 4, 'Day 5', 3, 'Low-Pulley Cable Glute Kickback', 'Glutes', 2, '11-12', '0'),
(3, 'November rain', 4, 'Day 5', 4, 'Seated Leg Curl Machine', 'Hamstrings', 4, '10-11', '0-1'),
(3, 'November rain', 4, 'Day 5', 5, 'Cable Pullover', 'Lats', 2, '10', '0'),
(4, 'Stranged', 0, 'Day 1', 0, 'Single-Leg Dumbbell Hip Thrust', 'Glutes', 2, '11-12', '0'),
(4, 'Stranged', 0, 'Day 1', 1, 'Barbell Lunges (Quad-Focus)', 'Quads', 2, '8-9', '0'),
(4, 'Stranged', 0, 'Day 1', 2, 'Single-Leg Leg Extension Machine', 'Quads', 2, '10', '0'),
(4, 'Stranged', 0, 'Day 1', 3, 'Lying Leg Curl Machine', 'Hamstrings', 2, '10-11', '1'),
(4, 'Stranged', 0, 'Day 1', 4, 'Cable Hip Abduction (Mid-Pulley)', 'Glutes', 2, '15-16', '0'),
(4, 'Stranged', 0, 'Day 1', 5, 'Calf Raise on 45° Leg Press (Lengthened Partials)', 'Calves', 2, '12', '0-1'),
(4, 'Stranged', 1, 'Day 2', 0, 'Neutral-Grip Lat Pulldown', 'Upper Back', 2, '9-10', '0'),
(4, 'Stranged', 1, 'Day 2', 1, 'Behind-the-Back Cable Lateral Raise (Mid-Height)', 'Side Delts', 2, '10-11', '0'),
(4, 'Stranged', 1, 'Day 2', 2, 'Standing Alternating Dumbbell Front Raises', 'Front Delts', 2, '18-20', '0'),
(4, 'Stranged', 1, 'Day 2', 3, 'Standing EZ-Bar Biceps Curl', 'Biceps', 1, '12', '0'),
(4, 'Stranged', 1, 'Day 2', 4, 'Standing EZ-Bar Biceps Curl', 'Biceps', 1, '11', '0'),
(4, 'Stranged', 1, 'Day 2', 5, 'V-Ups', 'Core', 3, '12', '1'),
(4, 'Stranged', 1, 'Day 2', 6, 'Hanging Knee Raises', 'Core', 3, '12', '0'),
(4, 'Stranged', 2, 'Day 3', 0, 'Hack Squat', 'Quads', 2, '9', '0-1'),
(4, 'Stranged', 2, 'Day 3', 1, 'Seated Leg Extension Machine', 'Quads', 2, '12-15', 'fallo'),
(4, 'Stranged', 2, 'Day 3', 2, '45° Back Extension', 'Glutes', 2, '8', '0-1'),
(4, 'Stranged', 2, 'Day 3', 3, 'Seated Hip Abduction Machine', 'Glutes', 2, '15', '0-1'),
(4, 'Stranged', 2, 'Day 3', 4, 'Lying Leg Curl Machine', 'Hamstrings', 2, '12', '0-1'),
(4, 'Stranged', 3, 'Day 4', 0, 'Seated Dumbbell Shoulder Press', 'Front Delts', 1, '8', '0'),
(4, 'Stranged', 3, 'Day 4', 1, 'Single-Arm Incline Dumbbell Lateral Raise', 'Side Delts', 2, '15-18', '0'),
(4, 'Stranged', 3, 'Day 4', 2, 'Single-Arm Lateral Raise (Long Partials)', 'Rear Delts', 2, '15', 'fallo'),
(4, 'Stranged', 3, 'Day 4', 3, 'Cable JM Press', 'Triceps', 2, '10-11', '0'),
(4, 'Stranged', 3, 'Day 4', 4, 'Eccentric Dragon Flag', 'Core', 3, '10-11', '0'),
(4, 'Stranged', 3, 'Day 4', 5, 'Bird Dog', 'Core', 3, '15', '0-1'),
(4, 'Stranged', 4, 'Day 5', 0, 'Pendulum Squat', 'Quads', 1, '6', '1-2'),
(4, 'Stranged', 4, 'Day 5', 1, 'Seated Leg Extension Machine', 'Quads', 2, '10-11', 'fallo'),
(4, 'Stranged', 4, 'Day 5', 2, 'Machine Hip Thrust', 'Glutes', 2, '9-10', '0'),
(4, 'Stranged', 4, 'Day 5', 3, 'Low-Pulley Cable Glute Kickback', 'Glutes', 2, '14-15', 'fallo'),
(4, 'Stranged', 4, 'Day 5', 4, 'Seated Leg Curl Machine', 'Hamstrings', 2, '13', 'fallo'),
(5, 'Girls just wanna have fun', 0, 'Day 1', 0, 'Single-Leg Dumbbell Hip Thrust', 'Glutes', 2, '12', '0'),
(5, 'Girls just wanna have fun', 0, 'Day 1', 1, 'Barbell Lunges (Quad-Focus)', 'Quads', 2, '8-9', '0'),
(5, 'Girls just wanna have fun', 0, 'Day 1', 2, 'Single-Leg Leg Extension Machine', 'Quads', 2, '12-15', 'fallo'),
(5, 'Girls just wanna have fun', 0, 'Day 1', 3, 'Lying Leg Curl Machine', 'Hamstrings', 2, '10-11', '0'),
(5, 'Girls just wanna have fun', 0, 'Day 1', 4, 'Cable Hip Abduction (Mid-Pulley)', 'Glutes', 2, '16', '0'),
(5, 'Girls just wanna have fun', 0, 'Day 1', 5, 'Calf Raise on 45° Leg Press (Lengthened Partials)', 'Calves', 2, '12-13', '0'),
(5, 'Girls just wanna have fun', 1, 'Day 2', 0, 'Neutral-Grip Lat Pulldown', 'Upper Back', 2, '', ''),
(5, 'Girls just wanna have fun', 1, 'Day 2', 1, 'Behind-the-Back Cable Lateral Raise (Mid-Height)', 'Side Delts', 2, '', ''),
(5, 'Girls just wanna have fun', 1, 'Day 2', 2, 'Standing Alternating Dumbbell Front Raises', 'Front Delts', 2, '', ''),
(5, 'Girls just wanna have fun', 1, 'Day 2', 3, 'Standing EZ-Bar Biceps Curl', 'Biceps', 1, '', ''),
(5, 'Girls just wanna have fun', 1, 'Day 2', 4, 'Standing EZ-Bar Biceps Curl', 'Biceps', 1, '', ''),
(5, 'Girls just wanna have fun', 1, 'Day 2', 5, 'V-Ups', 'Core', 3, '', ''),
(5, 'Girls just wanna have fun', 1, 'Day 2', 6, 'Hanging Knee Raises', 'Core', 3, '', ''),
(5, 'Girls just wanna have fun', 2, 'Day 3', 0, 'Hack Squat', 'Quads', 2, '', ''),
(5, 'Girls just wanna have fun', 2, 'Day 3', 1, 'Seated Leg Extension Machine', 'Quads', 2, '', ''),
(5, 'Girls just wanna have fun', 2, 'Day 3', 2, '45° Back Extension', 'Glutes', 2, '', ''),
(5, 'Girls just wanna have fun', 2, 'Day 3', 3, 'Seated Hip Abduction Machine', 'Glutes', 2, '', ''),
(5, 'Girls just wanna have fun', 2, 'Day 3', 4, 'Lying Leg Curl Machine', 'Hamstrings', 2, '', ''),
(5, 'Girls just wanna have fun', 3, 'Day 4', 0, 'Seated Dumbbell Shoulder Press', 'Front Delts', 1, '', ''),
(5, 'Girls just wanna have fun', 3, 'Day 4', 1, 'Single-Arm Incline Dumbbell Lateral Raise', 'Side Delts', 2, '', ''),
(5, 'Girls just wanna have fun', 3, 'Day 4', 2, 'Single-Arm Lateral Raise (Long Partials)', 'Rear Delts', 2, '', ''),
(5, 'Girls just wanna have fun', 3, 'Day 4', 3, 'Cable JM Press', 'Triceps', 2, '', ''),
(5, 'Girls just wanna have fun', 3, 'Day 4', 4, 'Eccentric Dragon Flag', 'Core', 3, '', ''),
(5, 'Girls just wanna have fun', 3, 'Day 4', 5, 'Bird Dog', 'Core', 3, '', ''),
(5, 'Girls just wanna have fun', 4, 'Day 5', 0, 'Pendulum Squat', 'Quads', 1, '', ''),
(5, 'Girls just wanna have fun', 4, 'Day 5', 1, 'Seated Leg Extension Machine', 'Quads', 2, '', ''),
(5, 'Girls just wanna have fun', 4, 'Day 5', 2, 'Machine Hip Thrust', 'Glutes', 2, '', ''),
(5, 'Girls just wanna have fun', 4, 'Day 5', 3, 'Low-Pulley Cable Glute Kickback', 'Glutes', 2, '', ''),
(5, 'Girls just wanna have fun', 4, 'Day 5', 4, 'Seated Leg Curl Machine', 'Hamstrings', 2, '', ''),
(6, 'im not the highway', 0, 'Day 1', 0, '45° Incline Leg Press', 'Quads', 3, '', ''),
(6, 'im not the highway', 0, 'Day 1', 1, 'Single-Leg Leg Extension Machine', 'Quads', 5, '', ''),
(6, 'im not the highway', 0, 'Day 1', 2, 'Single-Leg Dumbbell Hip Thrust', 'Glutes', 3, '', ''),
(6, 'im not the highway', 0, 'Day 1', 3, 'Lying Leg Curl Machine', 'Hamstrings', 5, '', ''),
(6, 'im not the highway', 0, 'Day 1', 4, 'Cable Hip Abduction (Mid-Pulley)', 'Glutes', 5, '', ''),
(6, 'im not the highway', 0, 'Day 1', 5, 'Calf Raise on 45° Leg Press (Lengthened Partials)', 'Calves', 3, '', ''),
(6, 'im not the highway', 1, 'Day 2', 0, 'Neutral-Grip Lat Pulldown', 'Upper Back', 2, '', ''),
(6, 'im not the highway', 1, 'Day 2', 1, 'Behind-the-Back Cable Lateral Raise (Mid-Height)', 'Front Delts', 4, '', ''),
(6, 'im not the highway', 1, 'Day 2', 2, 'Standing Alternating Dumbbell Front Raises', 'Side Delts', 4, '', ''),
(6, 'im not the highway', 1, 'Day 2', 3, 'Standing EZ-Bar Biceps Curl', 'Biceps', 2, '', ''),
(6, 'im not the highway', 1, 'Day 2', 4, 'V-Ups', 'Core', 3, '', ''),
(6, 'im not the highway', 2, 'Day 3', 0, 'V-Ups', 'Core', 1, '', ''),
(6, 'im not the highway', 2, 'Day 3', 1, 'Hanging Knee Raises', 'Core', 5, '', ''),
(6, 'im not the highway', 3, 'Day 4', 0, 'Dumbbell Bulgarian Split Squat (Glute)', 'Glutes', 4, '', ''),
(6, 'im not the highway', 3, 'Day 4', 1, 'Single-Leg Leg Extension Machine', 'Quads', 4, '', ''),
(6, 'im not the highway', 3, 'Day 4', 2, '45° Back Extension', 'Glutes', 4, '', ''),
(6, 'im not the highway', 3, 'Day 4', 3, 'Runner Glute Kickback', 'Glutes', 3, '', ''),
(6, 'im not the highway', 3, 'Day 4', 4, 'Seated Hip Abduction Machine', 'Glutes', 3, '', ''),
(6, 'im not the highway', 3, 'Day 4', 5, 'Seated Calf Raise', 'Calves', 3, '', ''),
(6, 'im not the highway', 4, 'Day 5', 0, 'Seated Dumbbell Shoulder Press', 'Front Delts', 4, '', ''),
(6, 'im not the highway', 4, 'Day 5', 1, 'Single-Arm Incline Dumbbell Lateral Raise', 'Side Delts', 4, '', ''),
(6, 'im not the highway', 4, 'Day 5', 2, 'Single-Arm Lateral Raise (Long Partials)', 'Rear Delts', 4, '', ''),
(6, 'im not the highway', 4, 'Day 5', 3, 'Cable JM Press', 'Triceps', 3, '', ''),
(6, 'im not the highway', 4, 'Day 5', 4, 'Eccentric Dragon Flag', 'Abs', 4, '', ''),
(6, 'im not the highway', 4, 'Day 5', 5, 'Bird Dog', 'Abs', 4, '', ''),
(6, 'im not the highway', 5, 'Day 6', 0, 'Stiff-Leg Dumbbell Romanian Deadlift', 'Hamstrings', 2, '', ''),
(6, 'im not the highway', 5, 'Day 6', 1, 'Seated Leg Extension Machine', 'Quads', 5, '', ''),
(6, 'im not the highway', 5, 'Day 6', 2, 'Seated Hip Adduction Machine', 'Adductors', 4, '', ''),
(6, 'im not the highway', 5, 'Day 6', 3, 'Low-Pulley Cable Glute Kickback', 'Glutes', 3, '', ''),
(6, 'im not the highway', 5, 'Day 6', 4, 'Seated Leg Curl Machine', 'Hamstrings', 2, '', ''),
(6, 'im not the highway', 5, 'Day 6', 5, 'Standing Barbell Row', 'Upper Back', 2, '', ''),
(7, 'Sunflower', 0, 'Day 1', 0, '45° Incline Leg Press', 'Quads', 3, '', ''),
(7, 'Sunflower', 0, 'Day 1', 1, 'Single-Leg Leg Extension Machine', 'Quads', 5, '', ''),
(7, 'Sunflower', 0, 'Day 1', 2, 'Single-Leg Dumbbell Hip Thrust', 'Glutes', 3, '', ''),
(7, 'Sunflower', 0, 'Day 1', 3, 'Lying Leg Curl Machine', 'Hamstrings', 5, '', ''),
(7, 'Sunflower', 0, 'Day 1', 4, 'Cable Hip Abduction (Mid-Pulley)', 'Glutes', 5, '', ''),
(7, 'Sunflower', 0, 'Day 1', 5, 'Calf Raise on 45° Leg Press (Lengthened Partials)', 'Calves', 3, '', ''),
(7, 'Sunflower', 1, 'Day 2', 0, 'Neutral-Grip Lat Pulldown', 'Upper Back', 2, '', ''),
(7, 'Sunflower', 1, 'Day 2', 1, 'Behind-the-Back Cable Lateral Raise (Mid-Height)', 'Front Delts', 4, '', ''),
(7, 'Sunflower', 1, 'Day 2', 2, 'Standing Alternating Dumbbell Front Raises', 'Side Delts', 4, '', ''),
(7, 'Sunflower', 1, 'Day 2', 3, 'Standing EZ-Bar Biceps Curl', 'Biceps', 2, '', ''),
(7, 'Sunflower', 1, 'Day 2', 4, 'V-Ups', 'Core', 4, '', ''),
(7, 'Sunflower', 1, 'Day 2', 5, 'Hanging Knee Raises', 'Core', 5, '', ''),
(7, 'Sunflower', 2, 'Day 3', 0, 'Dumbbell Bulgarian Split Squat (Glute)', 'Glutes', 4, '', ''),
(7, 'Sunflower', 2, 'Day 3', 1, 'Single-Leg Leg Extension Machine', 'Quads', 4, '', ''),
(7, 'Sunflower', 2, 'Day 3', 2, '45° Back Extension', 'Glutes', 4, '', ''),
(7, 'Sunflower', 2, 'Day 3', 3, 'Runner Glute Kickback', 'Glutes', 3, '', ''),
(7, 'Sunflower', 2, 'Day 3', 4, 'Seated Hip Abduction Machine', 'Glutes', 3, '', ''),
(7, 'Sunflower', 2, 'Day 3', 5, 'Seated Calf Raise', 'Calves', 3, '', ''),
(7, 'Sunflower', 3, 'Day 4', 0, 'Seated Dumbbell Shoulder Press', 'Front Delts', 4, '', ''),
(7, 'Sunflower', 3, 'Day 4', 1, 'Single-Arm Incline Dumbbell Lateral Raise', 'Side Delts', 4, '', ''),
(7, 'Sunflower', 3, 'Day 4', 2, 'Single-Arm Lateral Raise (Long Partials)', 'Rear Delts', 4, '', ''),
(7, 'Sunflower', 3, 'Day 4', 3, 'Cable JM Press', 'Triceps', 3, '', ''),
(7, 'Sunflower', 3, 'Day 4', 4, 'Eccentric Dragon Flag', 'Abs', 4, '', ''),
(7, 'Sunflower', 3, 'Day 4', 5, 'Bird Dog', 'Abs', 4, '', ''),
(7, 'Sunflower', 4, 'Day 5', 0, 'Stiff-Leg Dumbbell Romanian Deadlift', 'Hamstrings', 2, '', ''),
(7, 'Sunflower', 4, 'Day 5', 1, 'Seated Leg Extension Machine', 'Quads', 5, '', ''),
(7, 'Sunflower', 4, 'Day 5', 2, 'Seated Hip Adduction Machine', 'Adductors', 4, '', ''),
(7, 'Sunflower', 4, 'Day 5', 3, 'Low-Pulley Cable Glute Kickback', 'Glutes', 3, '', ''),
(7, 'Sunflower', 4, 'Day 5', 4, 'Seated Leg Curl Machine', 'Hamstrings', 2, '', ''),
(7, 'Sunflower', 4, 'Day 5', 5, 'Standing Barbell Row', 'Upper Back', 2, '', '');

  -- Ensure all exercises exist in the catalog (so plan_exercises can link).
  insert into exercises (owner_id, name, muscle_group)
  select uid, ename, (array_agg(egrp))[1] from pstruct p
  where not exists (select 1 from exercises e where (e.owner_id is null or e.owner_id = uid) and lower(trim(e.name)) = lower(trim(p.ename)))
  group by ename;

  -- Rebuild the week -> day -> exercise tree (leaves workouts untouched).
  delete from plan_weeks where plan_id = pid;

  insert into plan_weeks (plan_id, position, name)
  select pid, wpos, wname from (select distinct wpos, wname from pstruct) s;

  insert into plan_days (plan_id, week_id, position, name)
  select pid, w.id, s.dpos, s.dname
  from (select distinct wpos, dpos, dname from pstruct) s
  join plan_weeks w on w.plan_id = pid and w.position = s.wpos;

  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir)
  select pdy.id, p.epos,
    (select e.id from exercises e where (e.owner_id is null or e.owner_id = uid) and lower(trim(e.name)) = lower(trim(p.ename)) order by e.owner_id nulls last limit 1),
    p.sets, p.reps, nullif(p.rir,'')
  from pstruct p
  join plan_weeks w   on w.plan_id = pid and w.position = p.wpos
  join plan_days  pdy on pdy.week_id = w.id and pdy.position = p.dpos;

  raise notice 'WELLNESS estructurado: % semanas, % días, % ejercicios.',
    (select count(*) from plan_weeks where plan_id=pid),
    (select count(*) from plan_days where plan_id=pid),
    (select count(*) from plan_exercises pe join plan_days d on d.id=pe.day_id where d.plan_id=pid);
end $$;
