-- ─────────────────────────────────────────────────────────────
-- Leticia — log her first 3 weeks (days 1-4) with real weights.
-- Creates completed workouts so they show in her history & Progress.
-- Weights in kg; each weight applies to every set that day.
-- Sets = plan prescription; reps = plan lower bound.
-- ⚠️ EDIT Leticia's email before running.
-- Safe to re-run: it first deletes these 12 sessions, then re-creates them.
-- Sets use a running set_number so each exercise stays grouped and in order.
-- ─────────────────────────────────────────────────────────────
do $$
declare v_user uuid; v_plan uuid; v_wo uuid;
begin
  select id into v_user from users where lower(email) = lower('LETICIA_EMAIL_AQUI') limit 1;
  if v_user is null then raise exception 'No encontré a Leticia (revisa el correo).'; end if;
  select id into v_plan from plans where user_id = v_user order by is_active desc, created_at desc limit 1;

  delete from workouts where user_id = v_user and title in ('Semana 1 · Día 1', 'Semana 1 · Día 2', 'Semana 1 · Día 3', 'Semana 1 · Día 4', 'Semana 2 · Día 1', 'Semana 2 · Día 2', 'Semana 2 · Día 3', 'Semana 2 · Día 4', 'Semana 3 · Día 1', 'Semana 3 · Día 2', 'Semana 3 · Día 3', 'Semana 3 · Día 4');

  -- Semana 1 · Día 1
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 1 · Día 1', '2026-06-02'::timestamptz, 'Core (crunch). ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 1, 50, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 2, 50, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 3, 50, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 4, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 5, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 6, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 7, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 8, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 9, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 10, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 11, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 12, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 13, 25, 12, 'kg';

  -- Semana 1 · Día 2
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 1 · Día 2', '2026-06-03'::timestamptz, 'Cardio 15 min. ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 1, 20, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 2, 20, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 3, 20, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 4, 20, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 5, 20, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 6, 20, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 7, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 8, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 9, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 10, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 11, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 12, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 13, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 14, 15, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 15, 15, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 16, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 17, 20, 12, 'kg';

  -- Semana 1 · Día 3
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 1 · Día 3', '2026-06-05'::timestamptz, 'Core (plancha). ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 1, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 2, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 3, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 4, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 5, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 6, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 7, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 8, 20, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 9, 20, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 10, 20, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 11, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 12, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 13, 25, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 14, 25, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 15, 25, 20, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 16, 25, 20, 'kg';

  -- Semana 1 · Día 4
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 1 · Día 4', '2026-06-06'::timestamptz, 'Cardio 15 min. ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 1, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 2, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 3, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 4, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 5, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 6, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 7, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 8, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 9, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 10, 15, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 11, 15, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 12, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 13, 5, 12, 'kg';

  -- Semana 2 · Día 1
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 2 · Día 1', '2026-06-09'::timestamptz, 'Core (crunch). ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 1, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 2, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 3, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 4, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 5, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 6, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 7, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 8, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 9, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 10, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 11, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 12, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 13, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 14, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 15, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 16, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 17, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 18, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 19, 25, 12, 'kg';

  -- Semana 2 · Día 2
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 2 · Día 2', '2026-06-10'::timestamptz, 'Cardio 15 min. ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 1, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 2, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 3, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 4, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 5, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 6, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 7, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 8, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 9, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 10, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 11, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 12, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 13, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 14, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 15, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 16, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 17, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 18, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 19, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 20, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 21, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 22, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 23, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 24, 25, 12, 'kg';

  -- Semana 2 · Día 3
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 2 · Día 3', '2026-06-12'::timestamptz, 'Core (plancha). ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 1, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 2, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 3, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 4, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 5, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 6, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 7, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 8, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 9, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 10, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 11, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 12, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 13, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 14, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 15, 25, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 16, 25, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 17, 25, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 18, 25, 20, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 19, 25, 20, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 20, 25, 20, 'kg';

  -- Semana 2 · Día 4
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 2 · Día 4', '2026-06-13'::timestamptz, 'Cardio 15 min. ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 1, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 2, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 3, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 4, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 5, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 6, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 7, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 8, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 9, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 10, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 11, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 12, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 13, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 14, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 15, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 16, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 17, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 18, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 19, 5, 12, 'kg';

  -- Semana 3 · Día 1
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 3 · Día 1', '2026-06-16'::timestamptz, 'Core (crunch). ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 1, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 2, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 3, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 4, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 5, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 6, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 7, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 8, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 9, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 10, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 11, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 12, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 13, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 14, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 15, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 16, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 17, 30, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 18, 30, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 19, 30, 12, 'kg';

  -- Semana 3 · Día 2
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 3 · Día 2', '2026-06-17'::timestamptz, 'Cardio 15 min. ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 1, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 2, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 3, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 4, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 5, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 6, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 7, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 8, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 9, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 10, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 11, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 12, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 13, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 14, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 15, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 16, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 17, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 18, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 19, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 20, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 21, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 22, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 23, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 24, 25, 12, 'kg';

  -- Semana 3 · Día 3
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 3 · Día 3', '2026-06-19'::timestamptz, 'Core (plancha). ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 1, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 2, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 3, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 4, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 5, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 6, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 7, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 8, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 9, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 10, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 11, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 12, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 13, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 14, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 15, 30, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 16, 30, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 17, 30, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 18, 30, 20, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 19, 30, 20, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 20, 30, 20, 'kg';

  -- Semana 3 · Día 4
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 3 · Día 4', '2026-06-20'::timestamptz, 'Cardio 15 min. ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 1, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 2, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 3, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 4, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 5, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 6, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 7, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 8, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 9, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 10, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 11, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 12, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 13, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 14, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 15, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 16, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 17, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 18, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 19, 5, 12, 'kg';

  raise notice 'Listo: 12 entrenamientos (3 semanas x 4 días) registrados para Leticia.';
end $$;
