-- ─────────────────────────────────────────────────────────────
-- Lift & Inspire — Exercise catalog seed (translated from ES → EN)
-- Source: client's "DB_Ejercicios" spreadsheet (muscle group → exercises).
-- Run this once in the Supabase SQL editor (after schema-workouts.sql
-- and schema-exercise-owner.sql).
--
-- owner_id stays NULL so these become the shared/default library that
-- every member sees. Re-running is safe: rows already present (by name,
-- in the shared library) are skipped. 157 exercises across 10 groups.
-- ─────────────────────────────────────────────────────────────

insert into exercises (name, muscle_group, equipment, owner_id)
select v.name, v.muscle_group, v.equipment, null
from (values
  -- Quads
  ('Smith Machine Squat', 'Quads', 'Machine'),
  ('Hack Squat', 'Quads', 'Machine'),
  ('Anderson Squat', 'Quads', 'Barbell'),
  ('Front Squat', 'Quads', 'Barbell'),
  ('Bulgarian Split Squat', 'Quads', 'Dumbbell'),
  ('Dumbbell Squat', 'Quads', 'Dumbbell'),
  ('Sissy Squat', 'Quads', 'Bodyweight'),
  ('High-Bar Squat', 'Quads', 'Barbell'),
  ('High-Bar Squat (Feet Together)', 'Quads', 'Barbell'),
  ('Zercher Squat', 'Quads', 'Barbell'),
  ('Landmine Squat', 'Quads', 'Barbell'),
  ('Goblet Squat', 'Quads', 'Dumbbell'),
  ('Barbell Lunges', 'Quads', 'Barbell'),
  ('Dumbbell Lunges', 'Quads', 'Dumbbell'),
  ('Split Squat', 'Quads', 'Bodyweight'),
  ('Leg Press', 'Quads', 'Machine'),
  ('Single-Leg Press', 'Quads', 'Machine'),
  ('Leg Extension', 'Quads', 'Machine'),
  ('Front Jump Squat', 'Quads', 'Bodyweight'),
  -- Hamstrings
  ('Seated Leg Curl', 'Hamstrings', 'Machine'),
  ('Lying Leg Curl', 'Hamstrings', 'Machine'),
  ('Standing Leg Curl', 'Hamstrings', 'Machine'),
  ('Dumbbell Romanian Deadlift', 'Hamstrings', 'Dumbbell'),
  ('Barbell Romanian Deadlift', 'Hamstrings', 'Barbell'),
  ('Conventional Deadlift', 'Hamstrings', 'Barbell'),
  ('Deficit Deadlift', 'Hamstrings', 'Barbell'),
  ('Zercher Deadlift', 'Hamstrings', 'Barbell'),
  ('Stiff-Leg Deadlift', 'Hamstrings', 'Barbell'),
  ('Nordic Curl', 'Hamstrings', 'Bodyweight'),
  -- Glutes
  ('Hip Thrust', 'Glutes', 'Barbell'),
  ('KAS Glute Bridge', 'Glutes', 'Barbell'),
  ('Cable Glute Kickback (Runner)', 'Glutes', 'Cable'),
  ('Cable Glute Kickback', 'Glutes', 'Cable'),
  ('Cable Lateral Kickback', 'Glutes', 'Cable'),
  ('Hip Abduction', 'Glutes', 'Machine'),
  ('Hip Abductor Machine', 'Glutes', 'Machine'),
  ('Cable Hip Adduction', 'Glutes', 'Cable'),
  ('Clamshells', 'Glutes', 'Bodyweight'),
  ('Back Extension (Roman Chair)', 'Glutes', 'Bodyweight'),
  ('Cable Pull-Through', 'Glutes', 'Cable'),
  ('Deficit Bulgarian Split Squat', 'Glutes', 'Dumbbell'),
  ('Glute Bridge', 'Glutes', 'Bodyweight'),
  -- Calves
  ('Standing Calf Raise', 'Calves', 'Machine'),
  ('Machine Calf Raise', 'Calves', 'Machine'),
  ('Calf Raise (Legs Extended)', 'Calves', 'Machine'),
  ('Tibialis Raise (Costurera)', 'Calves', 'Bodyweight'),
  ('Leg Press Calf Raise', 'Calves', 'Machine'),
  -- Chest
  ('Barbell Bench Press', 'Chest', 'Barbell'),
  ('Slight Incline Barbell Bench Press', 'Chest', 'Barbell'),
  ('Incline Bench Press', 'Chest', 'Barbell'),
  ('Dumbbell Bench Press', 'Chest', 'Dumbbell'),
  ('Slight Incline Dumbbell Press', 'Chest', 'Dumbbell'),
  ('Incline Dumbbell Press', 'Chest', 'Dumbbell'),
  ('Dumbbell Fly', 'Chest', 'Dumbbell'),
  ('Pec Deck (Machine Fly)', 'Chest', 'Machine'),
  ('Parallel Bar Dips', 'Chest', 'Bodyweight'),
  ('Low-to-High Cable Crossover', 'Chest', 'Cable'),
  ('Spoto Press', 'Chest', 'Barbell'),
  ('Push-Ups', 'Chest', 'Bodyweight'),
  ('Larsen Press', 'Chest', 'Barbell'),
  ('Close-Grip Larsen Press', 'Chest', 'Barbell'),
  -- Back
  ('Neutral-Grip Pull-Ups', 'Back', 'Bodyweight'),
  ('Close-Grip Pull-Ups', 'Back', 'Bodyweight'),
  ('Chin-Ups', 'Back', 'Bodyweight'),
  ('Barbell Row', 'Back', 'Barbell'),
  ('Dumbbell Row', 'Back', 'Dumbbell'),
  ('Single-Arm Dumbbell Row', 'Back', 'Dumbbell'),
  ('Incline Bench Row', 'Back', 'Dumbbell'),
  ('T-Bar Row', 'Back', 'Barbell'),
  ('Machine Pulldown', 'Back', 'Machine'),
  ('Underhand Lat Pulldown', 'Back', 'Cable'),
  ('Overhand Lat Pulldown', 'Back', 'Cable'),
  ('Neutral-Grip Lat Pulldown', 'Back', 'Cable'),
  ('Close-Grip (V-Bar) Lat Pulldown', 'Back', 'Cable'),
  ('Wide-Grip Lat Pulldown', 'Back', 'Cable'),
  ('Cable Row', 'Back', 'Cable'),
  ('Machine Row', 'Back', 'Machine'),
  ('Single-Arm Machine Row', 'Back', 'Machine'),
  ('Standing Low Cable Row', 'Back', 'Cable'),
  ('Standing High Cable Row', 'Back', 'Cable'),
  ('Pulldown', 'Back', 'Cable'),
  ('Helms Row', 'Back', 'Dumbbell'),
  -- Biceps
  ('Barbell Curl', 'Biceps', 'Barbell'),
  ('EZ-Bar Curl', 'Biceps', 'Barbell'),
  ('T-Bar Curl', 'Biceps', 'Barbell'),
  ('Straight-Bar Curl', 'Biceps', 'Barbell'),
  ('Reverse-Grip Barbell Curl', 'Biceps', 'Barbell'),
  ('Supinated Dumbbell Curl', 'Biceps', 'Dumbbell'),
  ('Hammer Curl', 'Biceps', 'Dumbbell'),
  ('Dumbbell Curl', 'Biceps', 'Dumbbell'),
  ('Incline Dumbbell Curl', 'Biceps', 'Dumbbell'),
  ('Straight-Bar Preacher Curl', 'Biceps', 'Barbell'),
  ('EZ-Bar Preacher Curl', 'Biceps', 'Barbell'),
  ('Concentration Curl', 'Biceps', 'Dumbbell'),
  ('Machine Curl', 'Biceps', 'Machine'),
  ('Low Cable Curl', 'Biceps', 'Cable'),
  ('High Cable Curl', 'Biceps', 'Cable'),
  -- Triceps
  ('EZ-Bar Skull Crusher', 'Triceps', 'Barbell'),
  ('T-Bar Skull Crusher', 'Triceps', 'Barbell'),
  ('Straight-Bar Skull Crusher', 'Triceps', 'Barbell'),
  ('Dumbbell Skull Crusher', 'Triceps', 'Dumbbell'),
  ('Bench Dips', 'Triceps', 'Bodyweight'),
  ('Machine Dips', 'Triceps', 'Machine'),
  ('Wall Dips', 'Triceps', 'Bodyweight'),
  ('Dumbbell Tricep Kickback', 'Triceps', 'Dumbbell'),
  ('Close-Grip Bench Press', 'Triceps', 'Barbell'),
  ('Two-Hand Overhead Extension', 'Triceps', 'Dumbbell'),
  ('Single-Arm Overhead Extension', 'Triceps', 'Dumbbell'),
  ('Two-Dumbbell Overhead Extension', 'Triceps', 'Dumbbell'),
  ('Cable Pushdown (Bar)', 'Triceps', 'Cable'),
  ('Cable Pushdown (Rope)', 'Triceps', 'Cable'),
  ('Cable Pushdown (V-Bar)', 'Triceps', 'Cable'),
  ('Overhead Cable Extension', 'Triceps', 'Cable'),
  ('Cable Tricep Kickback', 'Triceps', 'Cable'),
  ('Diamond Push-Ups', 'Triceps', 'Bodyweight'),
  -- Shoulders
  ('Barbell Overhead Press', 'Shoulders', 'Barbell'),
  ('Dumbbell Shoulder Press', 'Shoulders', 'Dumbbell'),
  ('Machine Shoulder Press', 'Shoulders', 'Machine'),
  ('Ranger Press', 'Shoulders', 'Barbell'),
  ('Dumbbell Front Press', 'Shoulders', 'Dumbbell'),
  ('Arnold Press', 'Shoulders', 'Dumbbell'),
  ('Full Lateral Raises', 'Shoulders', 'Dumbbell'),
  ('Machine Lateral Raise', 'Shoulders', 'Machine'),
  ('Dumbbell Lateral Raise', 'Shoulders', 'Dumbbell'),
  ('Single-Arm Dumbbell Lateral Raise', 'Shoulders', 'Dumbbell'),
  ('Cross-Cable Lateral Raise', 'Shoulders', 'Cable'),
  ('Single-Arm Cable Lateral Raise', 'Shoulders', 'Cable'),
  ('Cable Front Raise', 'Shoulders', 'Cable'),
  ('Front Raise', 'Shoulders', 'Dumbbell'),
  ('Single-Arm Front Raise', 'Shoulders', 'Dumbbell'),
  ('Neutral-Grip Front Raise', 'Shoulders', 'Dumbbell'),
  ('Standing Bent-Over Reverse Fly', 'Shoulders', 'Dumbbell'),
  ('Seated Bent-Over Reverse Fly', 'Shoulders', 'Dumbbell'),
  ('Prone Bench Reverse Fly', 'Shoulders', 'Dumbbell'),
  ('Barbell Upright Row', 'Shoulders', 'Barbell'),
  ('Dumbbell Upright Row', 'Shoulders', 'Dumbbell'),
  ('Cable Upright Row', 'Shoulders', 'Cable'),
  ('Shrugs', 'Shoulders', 'Dumbbell'),
  ('Reverse Pec Deck', 'Shoulders', 'Machine'),
  ('Front Raise (Plate/Barbell/Dumbbell)', 'Shoulders', ''),
  ('Face Pull', 'Shoulders', 'Cable'),
  -- Core
  ('Crunch', 'Core', 'Bodyweight'),
  ('Bench Sit-Ups', 'Core', 'Bodyweight'),
  ('Leg Raises', 'Core', 'Bodyweight'),
  ('Russian Twist', 'Core', 'Bodyweight'),
  ('Lying Vertical Leg Raises', 'Core', 'Bodyweight'),
  ('Vertical Bench Hip Raise', 'Core', 'Bodyweight'),
  ('Hanging Hip Raise', 'Core', 'Bodyweight'),
  ('Seated Machine Crunch', 'Core', 'Machine'),
  ('Cable Crunch', 'Core', 'Cable'),
  ('Scissor Kicks', 'Core', 'Bodyweight'),
  ('Low Plank (Forearm Plank)', 'Core', 'Bodyweight'),
  ('High Plank', 'Core', 'Bodyweight'),
  ('Ab Rollout', 'Core', ''),
  ('Pallof Press', 'Core', 'Cable'),
  ('Farmer''s Walk', 'Core', 'Dumbbell'),
  ('Single-Arm Farmer''s Walk', 'Core', 'Dumbbell')
) as v(name, muscle_group, equipment)
where not exists (
  select 1 from exercises e
  where lower(e.name) = lower(v.name) and e.owner_id is null
);
