-- ─────────────────────────────────────────────────────────────
-- Claudia — Powerbuilding Intro (4 semanas x 5 días). NO activo.
-- Ejecutar una vez en el editor SQL de Supabase (producción).
-- STEP 1 crea los ejercicios (propios de Claudia) si faltan.
-- STEP 2 crea el plan como INACTIVO (no toca su plan activo actual).
-- Reejecutar crea OTRO plan; borra duplicados desde /admin si hace falta.
-- ⚠️ Revisa el correo de Claudia en la línea marcada antes de correr.
-- ─────────────────────────────────────────────────────────────

do $$
declare v_user uuid; v_plan uuid; v_week uuid; v_day uuid;
begin
  select id into v_user from users where lower(email) = lower('yaczoe@gmail.com'); -- ⚠️ correo de Claudia
  if v_user is null then raise exception 'No encontré a Claudia (revisa el correo).'; end if;

  -- STEP 1 — ejercicios propios de Claudia (solo los que falten)
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Abducción de cadera de pie con grillete en polea baja', 'Glúteos', 'Polea' where not exists (select 1 from exercises e where lower(e.name)=lower('Abducción de cadera de pie con grillete en polea baja') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Abducción de cadera sentado en máquina', 'Glúteos', 'Máquina' where not exists (select 1 from exercises e where lower(e.name)=lower('Abducción de cadera sentado en máquina') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Copa a una mano con polea intermedia (Estabilidad adicional)', 'Hombros', 'Polea' where not exists (select 1 from exercises e where lower(e.name)=lower('Copa a una mano con polea intermedia (Estabilidad adicional)') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Crunch abdominal', 'Abdomen', 'Peso corporal' where not exists (select 1 from exercises e where lower(e.name)=lower('Crunch abdominal') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Curl de bíceps con soga polea baja', 'Bíceps', 'Polea' where not exists (select 1 from exercises e where lower(e.name)=lower('Curl de bíceps con soga polea baja') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Curl para isquiosurales acostado en máquina', 'Isquiosurales', 'Máquina' where not exists (select 1 from exercises e where lower(e.name)=lower('Curl para isquiosurales acostado en máquina') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Curl para isquiosurales sentado en máquina', 'Isquiosurales', 'Máquina' where not exists (select 1 from exercises e where lower(e.name)=lower('Curl para isquiosurales sentado en máquina') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Dominada prono con lastre', 'Espalda', 'Peso corporal' where not exists (select 1 from exercises e where lower(e.name)=lower('Dominada prono con lastre') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Elevaciones laterales cruzadas con polea en posición intermedia - parciales largas', 'Hombros', 'Polea' where not exists (select 1 from exercises e where lower(e.name)=lower('Elevaciones laterales cruzadas con polea en posición intermedia - parciales largas') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Elevaciones laterales de pie con mancuernas', 'Hombros', 'Mancuernas' where not exists (select 1 from exercises e where lower(e.name)=lower('Elevaciones laterales de pie con mancuernas') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Extensión de rodilla unilateral en máquina', 'Cuádriceps', 'Máquina' where not exists (select 1 from exercises e where lower(e.name)=lower('Extensión de rodilla unilateral en máquina') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Extensión para cuádriceps sentado en máquina', 'Cuádriceps', 'Máquina' where not exists (select 1 from exercises e where lower(e.name)=lower('Extensión para cuádriceps sentado en máquina') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Fondos para tríceps en paralelas', 'Tríceps', 'Peso corporal' where not exists (select 1 from exercises e where lower(e.name)=lower('Fondos para tríceps en paralelas') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Hip thrust tradicional con barra - excéntrico 3-4 segundos', 'Glúteos', 'Barra' where not exists (select 1 from exercises e where lower(e.name)=lower('Hip thrust tradicional con barra - excéntrico 3-4 segundos') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'JM Press con cable', 'Tríceps', 'Polea' where not exists (select 1 from exercises e where lower(e.name)=lower('JM Press con cable') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Patada para glúteo con grillete en polea baja', 'Glúteos', 'Polea' where not exists (select 1 from exercises e where lower(e.name)=lower('Patada para glúteo con grillete en polea baja') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Peso muerto convencional', 'Isquiosurales', 'Barra' where not exists (select 1 from exercises e where lower(e.name)=lower('Peso muerto convencional') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Prensa militar sentado con mancuernas', 'Hombros', 'Mancuernas' where not exists (select 1 from exercises e where lower(e.name)=lower('Prensa militar sentado con mancuernas') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Press banca', 'Pectorales', 'Barra' where not exists (select 1 from exercises e where lower(e.name)=lower('Press banca') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Press de Pecho Inclinado con Mancuernas', 'Pectorales', 'Mancuernas' where not exists (select 1 from exercises e where lower(e.name)=lower('Press de Pecho Inclinado con Mancuernas') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Puente de glúteo', 'Glúteos', 'Peso corporal' where not exists (select 1 from exercises e where lower(e.name)=lower('Puente de glúteo') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Remo sentado en máquina', 'Espalda', 'Máquina' where not exists (select 1 from exercises e where lower(e.name)=lower('Remo sentado en máquina') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Sentadilla búlgara con barra', 'Cuádriceps', 'Barra' where not exists (select 1 from exercises e where lower(e.name)=lower('Sentadilla búlgara con barra') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Sentadilla frontal con barra', 'Cuádriceps', 'Barra' where not exists (select 1 from exercises e where lower(e.name)=lower('Sentadilla frontal con barra') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'Sentadilla libre de competencia', 'Cuádriceps', 'Barra' where not exists (select 1 from exercises e where lower(e.name)=lower('Sentadilla libre de competencia') and (e.owner_id = v_user or e.owner_id is null));
  insert into exercises (owner_id, name, muscle_group, equipment) select v_user, 'bird dog', 'Abdomen', 'Peso corporal' where not exists (select 1 from exercises e where lower(e.name)=lower('bird dog') and (e.owner_id = v_user or e.owner_id is null));

  -- STEP 2 — el plan (INACTIVO)
  insert into plans (user_id, name, objective, weeks, is_active, next_index, current_week)
    values (v_user, 'Powerbuilding Intro', 'Powerbuilding — fuerza + hipertrofia', 4, false, 0, 0) returning id into v_plan;

  insert into plan_weeks (plan_id, position, name, notes) values (v_plan, 0, 'Semana 1', '') returning id into v_week;
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 0, 'Día 1', '≈68 min · Cuádriceps (7), Pectorales (6), Tríceps (3), Abductores de cadera (4)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Sentadilla libre de competencia') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Press banca') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Press de Pecho Inclinado con Mancuernas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Extensión de rodilla unilateral en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('JM Press con cable') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('Abducción de cadera de pie con grillete en polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 1, 'Día 2', '≈87 min · Isquiosurales (7), Espalda alta (3), Dorsales (3), Glúteos (6), Bíceps (3), Abdomen (3)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Peso muerto convencional') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Dominada prono con lastre') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Remo sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Hip thrust tradicional con barra - excéntrico 3-4 segundos') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Curl para isquiosurales acostado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('Patada para glúteo con grillete en polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 6, (select id from exercises where lower(name)=lower('Curl de bíceps con soga polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 7, (select id from exercises where lower(name)=lower('Crunch abdominal') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 2, 'Día 3', '≈56 min · Pectorales (2), Tríceps (5), Hombro anterior (2), Hombro lateral (3), Abdomen (3)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Press banca') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Fondos para tríceps en paralelas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Prensa militar sentado con mancuernas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Copa a una mano con polea intermedia (Estabilidad adicional)') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Elevaciones laterales cruzadas con polea en posición intermedia - parciales largas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('bird dog') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 3, 'Día 4', '≈60 min · Cuádriceps (10), Abductores de cadera (5), Abdomen (3)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Sentadilla frontal con barra') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Sentadilla búlgara con barra') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Extensión para cuádriceps sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Abducción de cadera sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Crunch abdominal') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 4, 'Día 5', '≈79 min · Pectorales (2), Isquiosurales (7), Glúteos (6), Espalda alta (2), Dorsales (1), Hombro lateral (4)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Press banca') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Peso muerto convencional') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Puente de glúteo') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Dominada prono con lastre') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Remo sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 1, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('Curl para isquiosurales sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 6, (select id from exercises where lower(name)=lower('Elevaciones laterales de pie con mancuernas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 7, (select id from exercises where lower(name)=lower('Patada para glúteo con grillete en polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';

  insert into plan_weeks (plan_id, position, name, notes) values (v_plan, 1, 'Semana 2', '') returning id into v_week;
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 0, 'Día 1', '≈68 min · Cuádriceps (7), Pectorales (6), Tríceps (3), Abductores de cadera (4)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Sentadilla libre de competencia') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Press banca') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Press de Pecho Inclinado con Mancuernas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Extensión de rodilla unilateral en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('JM Press con cable') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('Abducción de cadera de pie con grillete en polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 1, 'Día 2', '≈84 min · Isquiosurales (7), Espalda alta (2), Dorsales (2), Glúteos (6), Bíceps (3), Abdomen (4)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Peso muerto convencional') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Dominada prono con lastre') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Remo sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Hip thrust tradicional con barra - excéntrico 3-4 segundos') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Curl para isquiosurales acostado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('Patada para glúteo con grillete en polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 6, (select id from exercises where lower(name)=lower('Curl de bíceps con soga polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 7, (select id from exercises where lower(name)=lower('Crunch abdominal') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 2, 'Día 3', '≈63 min · Pectorales (3), Tríceps (5), Hombro anterior (2), Hombro lateral (3), Abdomen (5)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Press banca') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Fondos para tríceps en paralelas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Prensa militar sentado con mancuernas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Copa a una mano con polea intermedia (Estabilidad adicional)') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Elevaciones laterales cruzadas con polea en posición intermedia - parciales largas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('bird dog') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 3, 'Día 4', '≈65 min · Cuádriceps (10), Abductores de cadera (5), Abdomen (5)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Sentadilla frontal con barra') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Sentadilla búlgara con barra') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Extensión para cuádriceps sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Abducción de cadera sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Crunch abdominal') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 4, 'Día 5', '≈87 min · Pectorales (5), Isquiosurales (7), Glúteos (6), Espalda alta (2), Dorsales (1), Hombro lateral (4)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Press banca') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Peso muerto convencional') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Puente de glúteo') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Dominada prono con lastre') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Remo sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 1, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('Curl para isquiosurales sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 6, (select id from exercises where lower(name)=lower('Elevaciones laterales de pie con mancuernas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 7, (select id from exercises where lower(name)=lower('Patada para glúteo con grillete en polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';

  insert into plan_weeks (plan_id, position, name, notes) values (v_plan, 2, 'Semana 3', '') returning id into v_week;
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 0, 'Día 1', '≈68 min · Cuádriceps (7), Pectorales (6), Tríceps (3), Abductores de cadera (4)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Sentadilla libre de competencia') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Press banca') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Press de Pecho Inclinado con Mancuernas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Extensión de rodilla unilateral en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('JM Press con cable') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('Abducción de cadera de pie con grillete en polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 1, 'Día 2', '≈84 min · Isquiosurales (7), Espalda alta (2), Dorsales (2), Glúteos (6), Bíceps (3), Abdomen (4)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Peso muerto convencional') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Dominada prono con lastre') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Remo sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Hip thrust tradicional con barra - excéntrico 3-4 segundos') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Curl para isquiosurales acostado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('Patada para glúteo con grillete en polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 6, (select id from exercises where lower(name)=lower('Curl de bíceps con soga polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 7, (select id from exercises where lower(name)=lower('Crunch abdominal') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 2, 'Día 3', '≈63 min · Pectorales (3), Tríceps (5), Hombro anterior (2), Hombro lateral (3), Abdomen (5)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Press banca') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Fondos para tríceps en paralelas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Prensa militar sentado con mancuernas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Copa a una mano con polea intermedia (Estabilidad adicional)') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Elevaciones laterales cruzadas con polea en posición intermedia - parciales largas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('bird dog') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 3, 'Día 4', '≈65 min · Cuádriceps (10), Abductores de cadera (5), Abdomen (5)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Sentadilla frontal con barra') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Sentadilla búlgara con barra') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Extensión para cuádriceps sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Abducción de cadera sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Crunch abdominal') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 4, 'Día 5', '≈87 min · Pectorales (5), Isquiosurales (7), Glúteos (6), Espalda alta (2), Dorsales (1), Hombro lateral (4)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Press banca') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Peso muerto convencional') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Puente de glúteo') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Dominada prono con lastre') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Remo sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 1, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('Curl para isquiosurales sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 6, (select id from exercises where lower(name)=lower('Elevaciones laterales de pie con mancuernas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 7, (select id from exercises where lower(name)=lower('Patada para glúteo con grillete en polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';

  insert into plan_weeks (plan_id, position, name, notes) values (v_plan, 3, 'Semana 4', '') returning id into v_week;
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 0, 'Día 1', '≈68 min · Cuádriceps (7), Pectorales (6), Tríceps (3), Abductores de cadera (4)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Sentadilla libre de competencia') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Press banca') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Press de Pecho Inclinado con Mancuernas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Extensión de rodilla unilateral en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('JM Press con cable') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('Abducción de cadera de pie con grillete en polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 1, 'Día 2', '≈84 min · Isquiosurales (7), Espalda alta (2), Dorsales (2), Glúteos (6), Bíceps (3), Abdomen (4)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Peso muerto convencional') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Dominada prono con lastre') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Remo sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Hip thrust tradicional con barra - excéntrico 3-4 segundos') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Curl para isquiosurales acostado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('Patada para glúteo con grillete en polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 6, (select id from exercises where lower(name)=lower('Curl de bíceps con soga polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 7, (select id from exercises where lower(name)=lower('Crunch abdominal') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 2, 'Día 3', '≈63 min · Pectorales (3), Tríceps (5), Hombro anterior (2), Hombro lateral (3), Abdomen (5)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Press banca') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Fondos para tríceps en paralelas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Prensa militar sentado con mancuernas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Copa a una mano con polea intermedia (Estabilidad adicional)') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Elevaciones laterales cruzadas con polea en posición intermedia - parciales largas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('bird dog') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 3, 'Día 4', '≈65 min · Cuádriceps (10), Abductores de cadera (5), Abdomen (5)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Sentadilla frontal con barra') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Sentadilla búlgara con barra') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Extensión para cuádriceps sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Abducción de cadera sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Crunch abdominal') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_days (plan_id, week_id, position, name, notes) values (v_plan, v_week, 4, 'Día 5', '≈87 min · Pectorales (5), Isquiosurales (7), Glúteos (6), Espalda alta (2), Dorsales (1), Hombro lateral (4)') returning id into v_day;
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 0, (select id from exercises where lower(name)=lower('Press banca') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 5, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 1, (select id from exercises where lower(name)=lower('Peso muerto convencional') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 2, (select id from exercises where lower(name)=lower('Puente de glúteo') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 3, (select id from exercises where lower(name)=lower('Dominada prono con lastre') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 2, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 4, (select id from exercises where lower(name)=lower('Remo sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 1, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 5, (select id from exercises where lower(name)=lower('Curl para isquiosurales sentado en máquina') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 6, (select id from exercises where lower(name)=lower('Elevaciones laterales de pie con mancuernas') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 4, '', '', '';
  insert into plan_exercises (day_id, position, exercise_id, sets, reps, rir, notes) select v_day, 7, (select id from exercises where lower(name)=lower('Patada para glúteo con grillete en polea baja') and (owner_id = v_user or owner_id is null) order by owner_id nulls last limit 1), 3, '', '', '';

  raise notice 'Plan Powerbuilding Intro creado (inactivo) para Claudia.';
end $$;
