-- ─────────────────────────────────────────────────────────────
-- Leticia — log her first 3 weeks (days 1-4) with real weights.
-- Creates completed workouts so they show in her history & Progress.
-- Weights in kg; each weight applies to every set that day.
-- Sets = plan prescription; reps = plan lower bound.
-- ⚠️ EDIT Leticia's email before running. Re-running adds duplicates.
-- ─────────────────────────────────────────────────────────────
do $$
declare v_user uuid; v_plan uuid; v_wo uuid;
begin
  select id into v_user from users where lower(email) = lower('LETICIA_EMAIL_AQUI') limit 1;
  if v_user is null then raise exception 'No encontré a Leticia (revisa el correo).'; end if;
  select id into v_plan from plans where user_id = v_user order by is_active desc, created_at desc limit 1;

  -- Semana 1 · Día 1
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 1 · Día 1', '2026-06-02'::timestamptz, 'Core (crunch). ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 1, 50, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 2, 50, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 3, 50, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 1, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 2, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 1, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 2, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 1, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 2, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 1, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 2, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 1, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 2, 25, 12, 'kg';

  -- Semana 1 · Día 2
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 1 · Día 2', '2026-06-03'::timestamptz, 'Cardio 15 min. ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 1, 20, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 2, 20, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 3, 20, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 1, 20, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 2, 20, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 3, 20, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 1, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 2, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 1, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 2, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 3, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 1, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 2, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 1, 15, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 2, 15, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 1, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 2, 20, 12, 'kg';

  -- Semana 1 · Día 3
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 1 · Día 3', '2026-06-05'::timestamptz, 'Core (plancha). ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 1, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 2, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 3, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 1, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 2, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 3, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 4, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 1, 20, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 2, 20, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 3, 20, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 1, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 2, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 1, 25, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 2, 25, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 1, 25, 20, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 2, 25, 20, 'kg';

  -- Semana 1 · Día 4
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 1 · Día 4', '2026-06-06'::timestamptz, 'Cardio 15 min. ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 1, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 2, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 3, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 1, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 2, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 1, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 2, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 1, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 2, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 1, 15, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 2, 15, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 1, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 2, 5, 12, 'kg';

  -- Semana 2 · Día 1
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 2 · Día 1', '2026-06-09'::timestamptz, 'Core (crunch). ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 1, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 2, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 3, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 4, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 1, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 2, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 3, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 1, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 2, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 3, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 1, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 2, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 3, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 1, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 2, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 3, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 1, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 2, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 3, 25, 12, 'kg';

  -- Semana 2 · Día 2
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 2 · Día 2', '2026-06-10'::timestamptz, 'Cardio 15 min. ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 1, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 2, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 3, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 4, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 1, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 2, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 3, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 4, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 1, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 2, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 3, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 1, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 2, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 3, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 4, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 1, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 2, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 3, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 1, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 2, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 3, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 1, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 2, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 3, 25, 12, 'kg';

  -- Semana 2 · Día 3
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 2 · Día 3', '2026-06-12'::timestamptz, 'Core (plancha). ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 1, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 2, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 3, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 4, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 1, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 2, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 3, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 1, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 2, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 3, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 4, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 1, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 2, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 3, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 1, 25, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 2, 25, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 3, 25, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 1, 25, 20, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 2, 25, 20, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 3, 25, 20, 'kg';

  -- Semana 2 · Día 4
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 2 · Día 4', '2026-06-13'::timestamptz, 'Cardio 15 min. ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 1, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 2, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 3, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 4, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 1, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 2, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 3, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 1, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 2, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 3, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 1, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 2, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 3, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 1, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 2, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 3, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 1, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 2, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 3, 5, 12, 'kg';

  -- Semana 3 · Día 1
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 3 · Día 1', '2026-06-16'::timestamptz, 'Core (crunch). ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 1, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 2, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 3, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Smith Machine Hip Thrust') and owner_id is null limit 1), 'Smith Machine Hip Thrust', 4, 60, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 1, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 2, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Reverse Lunge') and owner_id is null limit 1), 'Reverse Lunge', 3, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 1, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 2, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Press') and owner_id is null limit 1), 'Leg Press', 3, 0, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 1, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 2, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Deficit Step Up') and owner_id is null limit 1), 'Deficit Step Up', 3, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 1, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 2, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Leg Extension') and owner_id is null limit 1), 'Leg Extension', 3, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 1, 30, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 2, 30, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 3, 30, 12, 'kg';

  -- Semana 3 · Día 2
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 3 · Día 2', '2026-06-17'::timestamptz, 'Cardio 15 min. ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 1, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 2, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 3, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Overhand Lat Pulldown') and owner_id is null limit 1), 'Overhand Lat Pulldown', 4, 25, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 1, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 2, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 3, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Pulldown') and owner_id is null limit 1), 'Pulldown', 4, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 1, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 2, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 3, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 1, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 2, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 3, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Single-Arm Cable Lateral Raise') and owner_id is null limit 1), 'Single-Arm Cable Lateral Raise', 4, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 1, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 2, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Bench Press') and owner_id is null limit 1), 'Dumbbell Bench Press', 3, 10, 8, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 1, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 2, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Low Cable Curl') and owner_id is null limit 1), 'Low Cable Curl', 3, 20, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 1, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 2, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Pushdown (Rope)') and owner_id is null limit 1), 'Cable Pushdown (Rope)', 3, 25, 12, 'kg';

  -- Semana 3 · Día 3
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 3 · Día 3', '2026-06-19'::timestamptz, 'Core (plancha). ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 1, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 2, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 3, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Barbell Romanian Deadlift') and owner_id is null limit 1), 'Barbell Romanian Deadlift', 4, 10, 6, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 1, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 2, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('KAS Glute Bridge') and owner_id is null limit 1), 'KAS Glute Bridge', 3, 15, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 1, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 2, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 3, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Lying Leg Curl') and owner_id is null limit 1), 'Lying Leg Curl', 4, 25, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 1, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 2, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Back Extension (Roman Chair)') and owner_id is null limit 1), 'Back Extension (Roman Chair)', 3, 0, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 1, 30, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 2, 30, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Cable Glute Kickback') and owner_id is null limit 1), 'Cable Glute Kickback', 3, 30, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 1, 30, 20, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 2, 30, 20, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hip Abduction') and owner_id is null limit 1), 'Hip Abduction', 3, 30, 20, 'kg';

  -- Semana 3 · Día 4
  insert into workouts (user_id, title, performed_at, notes, plan_id, weight_unit) values (v_user, 'Semana 3 · Día 4', '2026-06-20'::timestamptz, 'Cardio 15 min. ', v_plan, 'kg') returning id into v_wo;
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 1, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 2, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 3, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Machine Row') and owner_id is null limit 1), 'Machine Row', 4, 40, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 1, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 2, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Close-Grip (V-Bar) Lat Pulldown') and owner_id is null limit 1), 'Close-Grip (V-Bar) Lat Pulldown', 3, 25, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 1, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 2, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Dumbbell Lateral Raise') and owner_id is null limit 1), 'Dumbbell Lateral Raise', 3, 5, 10, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 1, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 2, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Face Pull') and owner_id is null limit 1), 'Face Pull', 3, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 1, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 2, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Hammer Curl') and owner_id is null limit 1), 'Hammer Curl', 3, 20, 15, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 1, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 2, 5, 12, 'kg';
  insert into workout_sets (workout_id, exercise_id, exercise_name, set_number, weight, reps, weight_unit) select v_wo, (select id from exercises where lower(name)=lower('Two-Hand Overhead Extension') and owner_id is null limit 1), 'Two-Hand Overhead Extension', 3, 5, 12, 'kg';

  raise notice 'Listo: 12 entrenamientos (3 semanas x 4 días) registrados para Leticia.';
end $$;
